/** Ikon per modul-id (proto/Icon.tsx-namn). Delas av railen och bottom-menyn. */
export const MODULE_ICONS: Record<string, string> = {
  hem: 'home',
  idag: 'message',
  min_oversikt: 'home',
  mina_aktiviteter: 'flow',
  inkorg: 'inbox',
  pagaende: 'spark',
  arshjul: 'calendar',
  uppdrag: 'flow',
  filer: 'doc',
  inflode: 'spark',
  startups: 'people',
  de_minimis: 'shield',
  investerare: 'graph',
  events: 'spark',
  community: 'people',
  education: 'cap',
  rapporter: 'doc',
  agenter: 'bolt',
  insights: 'graph',
  integrationer: 'link',
  anvandare: 'user',
  installningar: 'gear'
};
